name: Build Windows App

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Package Win app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:win:publish
