name: Build macOS App

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Package macOS app
        run: npm run build:mac --universal --publish always

      # - name: Upload macOS artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: macOS-build
      # #     path: dist/*.dmg
      # - name: Package macOS app
      #   run: npm run electron:build -- --mac --universal --publish always

      - name: Upload macOS Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:mac --publish always
